#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "wakey-server"
version = "0.1.0"
authors = ["Parth-Bathe0142 <parth.bathe0142@gmail.com>"]
description = "Server for the keyring application"

[[trigger.http]]
route = "/..."
component = "wakey-server"

[component.wakey-server]
source = "../target/wasm32-wasip1/release/wakey_server.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.wakey-server.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]